hello-container:
  image: realpage/alpine-bash:3.3
  volumes_from:
    - data-container

  command: sh /home/welcome-compose.sh


data-container:
  image: realpage/alpine-bash:3.3
  volumes:

    # Path on the host, relative to the Compose file
    - ./scripts:/home

  command: /bin/ash